/*
 * Copyright (c) 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: LPC54628J512
package_id: LPC54628J512ET180
mcu_data: ksdk2_0
processor_version: 6.0.1
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iocon.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
	BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B13, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI, pin_signal: PIO0_29/FC0_RXD_SDA_MOSI/CTIMER2_MAT3/SCT0_OUT8/TRACEDATA(2), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: A2, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO, pin_signal: PIO0_30/FC0_TXD_SCL_MISO/CTIMER0_MAT0/SCT0_OUT9/TRACEDATA(1), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitPins(void)
{
	/* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
	CLOCK_EnableClock(kCLOCK_Iocon);

	const uint32_t port0_pin29_config = (/* Pin is configured as FC0_RXD_SDA_MOSI */
			IOCON_PIO_FUNC1 |
			/* No addition pin function */
			IOCON_PIO_MODE_INACT |
			/* Input function is not inverted */
			IOCON_PIO_INV_DI |
			/* Enables digital function */
			IOCON_PIO_DIGITAL_EN |
			/* Input filter disabled */
			IOCON_PIO_INPFILT_OFF |
			/* Standard mode, output slew rate control is enabled */
			IOCON_PIO_SLEW_STANDARD |
			/* Open drain is disabled */
			IOCON_PIO_OPENDRAIN_DI);
	/* PORT0 PIN29 (coords: B13) is configured as FC0_RXD_SDA_MOSI */
	IOCON_PinMuxSet(IOCON, 0U, 29U, port0_pin29_config);

	const uint32_t port0_pin30_config = (/* Pin is configured as FC0_TXD_SCL_MISO */
			IOCON_PIO_FUNC1 |
			/* No addition pin function */
			IOCON_PIO_MODE_INACT |
			/* Input function is not inverted */
			IOCON_PIO_INV_DI |
			/* Enables digital function */
			IOCON_PIO_DIGITAL_EN |
			/* Input filter disabled */
			IOCON_PIO_INPFILT_OFF |
			/* Standard mode, output slew rate control is enabled */
			IOCON_PIO_SLEW_STANDARD |
			/* Open drain is disabled */
			IOCON_PIO_OPENDRAIN_DI);
	/* PORT0 PIN30 (coords: A2) is configured as FC0_TXD_SCL_MISO */
	IOCON_PinMuxSet(IOCON, 0U, 30U, port0_pin30_config);
	IOCON->PIO[3][23] = ((IOCON->PIO[3][23] &
			/* Mask bits to zero which are setting */
			(~(IOCON_PIO_FUNC_MASK | IOCON_PIO_I2CSLEW_MASK | IOCON_PIO_DIGIMODE_MASK)))

			/* Selects pin function.
			 * : PORT323 (pin C2) is configured as FC2_CTS_SDA_SSEL0. */
			| IOCON_PIO_FUNC(PIO323_FUNC_ALT1)

			/* Controls slew rate of I2C pad.
			 * : I2C mode. */
			| IOCON_PIO_I2CSLEW(PIO323_I2CSLEW_I2C_MODE)

			/* Select Analog/Digital mode.
			 * : Digital mode. */
			| IOCON_PIO_DIGIMODE(PIO323_DIGIMODE_DIGITAL));

	IOCON->PIO[3][24] = ((IOCON->PIO[3][24] &
			/* Mask bits to zero which are setting */
			(~(IOCON_PIO_FUNC_MASK | IOCON_PIO_I2CSLEW_MASK | IOCON_PIO_DIGIMODE_MASK)))

			/* Selects pin function.
			 * : PORT324 (pin E2) is configured as FC2_RTS_SCL_SSEL1. */
			| IOCON_PIO_FUNC(PIO324_FUNC_ALT1)

			/* Controls slew rate of I2C pad.
			 * : I2C mode. */
			| IOCON_PIO_I2CSLEW(PIO324_I2CSLEW_I2C_MODE)

			/* Select Analog/Digital mode.
			 * : Digital mode. */
			| IOCON_PIO_DIGIMODE(PIO324_DIGIMODE_DIGITAL));

}

void BOARD_InitLEDsPins(void)
{
	/* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
	CLOCK_EnableClock(kCLOCK_Iocon);
	/* Enables the clock for the GPIO2 module */
	CLOCK_EnableClock(kCLOCK_Gpio2);
	/* Enables the clock for the GPIO3 module */
	CLOCK_EnableClock(kCLOCK_Gpio3);

	gpio_pin_config_t LED3_config = {
			.pinDirection = kGPIO_DigitalOutput,
			.outputLogic = 0U
	};
	/* Initialize GPIO functionality on pin PIO2_2 (pin C3)  */
	GPIO_PinInit(BOARD_LED3_GPIO, BOARD_LED3_PORT, BOARD_LED3_PIN, &LED3_config);

	gpio_pin_config_t LED2_config = {
			.pinDirection = kGPIO_DigitalOutput,
			.outputLogic = 0U
	};
	/* Initialize GPIO functionality on pin PIO3_3 (pin A13)  */
	GPIO_PinInit(BOARD_LED2_GPIO, BOARD_LED2_PORT, BOARD_LED2_PIN, &LED2_config);

	gpio_pin_config_t LED1_config = {
			.pinDirection = kGPIO_DigitalOutput,
			.outputLogic = 0U
	};
	/* Initialize GPIO functionality on pin PIO3_14 (pin E3)  */
	GPIO_PinInit(BOARD_LED1_GPIO, BOARD_LED1_PORT, BOARD_LED1_PIN, &LED1_config);

	IOCON->PIO[2][2] = ((IOCON->PIO[2][2] &
			/* Mask bits to zero which are setting */
			(~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

			/* Selects pin function.
			 * : PORT22 (pin C3) is configured as PIO2_2. */
			| IOCON_PIO_FUNC(PIO22_FUNC_ALT0)

			/* Select Analog/Digital mode.
			 * : Digital mode. */
			| IOCON_PIO_DIGIMODE(PIO22_DIGIMODE_DIGITAL));

	IOCON->PIO[3][14] = ((IOCON->PIO[3][14] &
			/* Mask bits to zero which are setting */
			(~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

			/* Selects pin function.
			 * : PORT314 (pin E3) is configured as PIO3_14. */
			| IOCON_PIO_FUNC(PIO314_FUNC_ALT0)

			/* Select Analog/Digital mode.
			 * : Digital mode. */
			| IOCON_PIO_DIGIMODE(PIO314_DIGIMODE_DIGITAL));

	IOCON->PIO[3][3] = ((IOCON->PIO[3][3] &
			/* Mask bits to zero which are setting */
			(~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

			/* Selects pin function.
			 * : PORT33 (pin A13) is configured as PIO3_3. */
			| IOCON_PIO_FUNC(PIO33_FUNC_ALT0)

			/* Select Analog/Digital mode.
			 * : Digital mode. */
			| IOCON_PIO_DIGIMODE(PIO33_DIGIMODE_DIGITAL));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
